### ISSUE TITLE
create spadesCBM chapter for November SpaDES training

### ISSUE THREAD

**Issue by camillegiuliano** [PredictiveEcology/spadesCBMpython#1]
Training dates: November 19th-21st 

Note: GitHub won't let me assign myself to this task for whatever reason... seems to only be an issue with this specific task, oh well!

```[tasklist]
### Tasks
- [ ] Skeleton .qmd for training book chapter
- [ ] Fill out .qmd file for training book chapter
- [x] create training branches for all modules and cleanup comments in the code for training purposes
```

**Comment by camillegiuliano** [comment]
I have a very (VERY) basic skeleton .qmd file built, should we put this essentially empty draft file directly into the `predictiveecology.org` repo and work directly there or should I upload it in another repo for now and upload it to the webpage repo once it's somewhat fleshed out?

Training branches for all modules are made and development comments have been removed in those branches. Do we want to make a training branch of the `spadesCBMpython` repo where we can make training specific changes (i.e. changing to `useGit = FALSE`, module pointers to the training branches) or just make those changes directly into the code in the training .qmd file since that's where people will be accessing the training code anyway?

**Comment by cboisvenue** [comment]
The current (Nov 2024) version of the training chapter points to @training branches. Eventually this needs to point to @main branches.
